@base = http://localhost:3000

### Get first page (25)
GET {{base}}/api/data?limit=3&page=450
Accept: application/json

### Search Paris available with price range
GET {{base}}/api/data?city=Paris&availability=true&priceMin=200&priceMax=600&sortBy=pricePerNight&sortDir=asc&limit=25
Accept: application/json

### Full-text search q
GET {{base}}/api/data?q=beach
Accept: application/json

### Get single document by Mongo _id
GET {{base}}/api/data/68f0f9e9d1606ef2d099a9f6
Accept: application/json

### Full text search
GET {{base}}/api/data?q=beach&city=Salvador
Accept: application/json

### Get by source
GET {{base}}/api/data?source=source1&limit=25
Accept: application/json

### Get by price segment
GET {{base}}/api/data?priceSegment=low

### Filter by Prince range edge cases
GET {{base}}/api/data?priceMin=300&priceMax=300
Accept: application/json

### Pagination example (page 3, page size 10)
GET {{base}}/api/data?limit=10&skip=20&sortBy=createdAt&sortDir=desc
Accept: application/json


